### ISSUE TITLE
Issue with qtype_algebra_test::test_question_saving_simplemath

### ISSUE THREAD

**Issue by AdilIqbal95** [jmvedrine/moodle-qtype_algebra#10]
Hi Jean-Michel Vedrine,

We are experiencing this error when running this test:

1) qtype_algebra_test::test_question_saving_simplemath
Error: Call to undefined method qtype_algebra_test::assertAttributeEquals()

/var/www/html/question/type/algebra/tests/questiontype_test.php:112
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97

Thanks.

**Comment by jmvedrine** [comment]
Hello,
This probably caused by some change in the Moodle recent versions.
As mentionned in the readme: I am now retired and I stopped all Moodle related activities. This repository is here just for history and this work is not maintained any more. Feel free to fork it and modify it to suit your needs or improve compatibility with recent Moodle versions. Additionally you can consider contacting the Moodle team and become the new maintainer of this plugin. Thanks
